### ISSUE TITLE
ErrorMedia projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

### ISSUE THREAD

**Issue by Raj123456788** [valentingrigorean/webrtc-h113#1]
Hey @valentingrigorean : I have been stuck on this since 4 days now. Only happening for screencapture for Android 10+. OS
Not sure what I need to write in the service?

**Comment by valentingrigorean** [comment]
Hey, can you attach a sample or something?  Because I didn't need this feature.
You can check https://stackoverflow.com/questions/61276730/media-projections-require-a-foreground-service-of-type-serviceinfo-foreground-se

**Comment by Raj123456788** [comment]
@valentingrigorean : Thank you for the link. I have tried it all but still need to write a service and notificationchannel for a foregroundservice. You can run this repo on Android 10 device(PixelXL in my case) :
 https://github.com/njovy/AppRTCDemo/issues/85 **It only happens with Screenshare with apprtc**
But when I run this repo in AndroidStudio it works: https://github.com/agent10/androidwebrtcexample
I converted peerconnectionclient.java to C#. But in VS it gives me above error. I am unable to understand how it works in androidstudio but not in C#
using: google-webrtc-1.0.32006.aar
Let me know if you need me to send the C# code.


Also, when I tried building your repo I get build error  error CS0426: The type name 'EIP712Message' does not exist in the type 'StructuredData'

**Comment by valentingrigorean** [comment]
Can you provide the C# code I'm more fluent with C# then android(java)
I notice that https://github.com/njovy/AppRTCDemo is giving this error when https://github.com/agent10/androidwebrtcexample is working I didn't find any diff between implementations and requesting the permission

**Comment by Raj123456788** [comment]
Which Android version are you testing it on? Here is the C# code
[WebRtcImplementationCopy.txt](https://github.com/valentingrigorean/webrtc-h113/files/5844470/WebRtcImplementationCopy.txt)
If you convert https://github.com/agent10/androidwebrtcexample  to C#(only peerconnectionclient.java) you get foreground service error.

**Comment by Raj123456788** [comment]
webrtc-h113 gives  build error error CS0426: The type name 'EIP712Message' does not exist in the type 'StructuredData'. How can I fix this and run webrtc-h113?

**Comment by valentingrigorean** [comment]
> Which Android version are you testing it on? Here is the C# code
> [WebRtcImplementationCopy.txt](https://github.com/valentingrigorean/webrtc-h113/files/5844470/WebRtcImplementationCopy.txt)
> If you convert https://github.com/agent10/androidwebrtcexample to C#(only peerconnectionclient.java) you get foreground service error.

was emulator API 29

**Comment by Raj123456788** [comment]
I tested with emulator it works but same code does not work on physical device. Can you please try it on a physical device?
 does screencapture work for webrtc-h113 for API29 on physical device? Please tell me how to fix the bug and I will work try to understand.

**Comment by valentingrigorean** [comment]
I update the repo also provide a very basic sample and the capture is working I think the order does matter. Like you have to have first the Capture permission before you create VideoCapture/CreatePeerConnection. I tested on emulator API 28/29 also on a real device with Android 11

**Comment by Raj123456788** [comment]
Hey @valentingrigorean : I just followed the peerconnectionclient.cs for 
capturer.StartCapture(width, height, videoFps); 
	ex	{Java.Lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION ---> Android.OS.RemoteException: Remote stack trace: 	at com.android.server.media.projection.MediaProjectionManagerService$…}
