### ISSUE TITLE
Change TargetSDK to 29

### ISSUE THREAD

**Issue by Raj123456788** [valentingrigorean/webrtc-h113#5]
For Webrtc.sample.Droid: try `<uses-sdk android:minSdkVersion="24" android:targetSdkVersion="29" />`

	

Error 	ex	{Java.Lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION ---> Android.OS.RemoteException: Remote stack trace: 	at com.android.server.media.projection.MediaProjectionManagerService$…}	
<img width="1404" alt="Screen Shot 2021-01-23 at 2 19 30 PM" src="https://user-images.githubusercontent.com/16295521/105615517-30c2b680-5d86-11eb-9a24-fc719ee95f94.png">

**Comment by valentingrigorean** [comment]
Hey, at the moment I'm busy with work don't have time to fix this but you should take a look at 
https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services
or use target SDK 28 instead of 29. As this not related to the binding I will close this issue.

**Comment by Raj123456788** [comment]
Hey @valentingrigorean : I wrote a foreground service and tried everything on github and stackoverflow. It still keeps giving me the same error despite writing the Foregroundservice.

**Comment by Raj123456788** [comment]
https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/ 
Got it working: Please follow steps to create a service and this is different than .java https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/

**Comment by valentingrigorean** [comment]
@Raj123456788 I'm glad u made it working. Worst case you use SDK target 28

**Comment by Raj123456788** [comment]
@valentingrigorean: Hello, I understand why you added StatsReport.Value in Metadata.xml.
```
<attr path="/api/package[@name='org.webrtc']/class[@name='StatsReport.Value']" name="name">StatsValue
    </attr>
```


But why did you add below code
```
    <attr path="/api/package[@name='org.webrtc']/class[@name='SessionDescription']/field[@name='type']" name="managedName">SdpType
    </attr>
    <attr path="/api/package[@name='org.webrtc']/interface[@name='PeerConnection.Observer']/method[@name='onConnectionChange' and count(parameter)=1 and parameter[1][@type='org.webrtc.PeerConnection.PeerConnectionState']]" name="abstract">true</attr>
```


Is there any documentation you follow? I know https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/customizing-bindings/java-bindings-metadata

**Comment by valentingrigorean** [comment]
I don't recall why I did it but I think for second 1 was not generating the C# method.

You can try and remove it and see if still builds :)

**Comment by Raj123456788** [comment]
It does build 👍  I need to learn the art of fixing the Binding bugs editing the Metadata.xml if you have links please share :) Thanks!

**Comment by valentingrigorean** [comment]
i don't just try and error and looking through another binding from xamarin team or other libraries :)
But you have to check if the type exists in C# :P

Check if you can access onConnectionChange without that line :)
